version: '2'
services:
  app:
    build: .
    working_dir: /go/src/github.com/alexandrevicenzi/go-chat
    command: go run main.go
    volumes:
     - .:/go/src/github.com/alexandrevicenzi/go-chat
    ports:
      - 8000:8000
